### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Prakyy** [xubowenhaoren/OPLiftToWake#1]
Any idea how to implement this feature in my personal custom rom? I have been trying to add a lift to wake functionality in my rom but couldn't and now I found this app and tested works good.

Now I want to use this code in my ROM but without the app (I will give all credits to you obviously) but the app might be considered bloat by my users.

Can you help get this feature in my ROM??

**Comment by xubowenhaoren** [comment]
See https://github.com/LineageOS/android_device_oneplus_sm8150-common/tree/lineage-17.1/doze/src/org/lineageos/settings/doze

**Comment by Prakyy** [comment]
Thanks for that, maybe you could give me some direction as to how to put it in the rom?

**Comment by Prakyy** [comment]
Btw, my rom already has a lift to wake feature but it turns on ambient display

**Comment by xubowenhaoren** [comment]
I suggest contacting the author of the repo above. After all, the repo above is a full ROM build.
