### ISSUE TITLE
Auto-Start App after Booting up

### ISSUE THREAD

**Issue by eliasacab** [xubowenhaoren/OPLiftToWake#2]
Is there a way to have the app auto start when the system boots up? I find I have to manually open the app after booting up the phone. Thanks!

**Comment by xubowenhaoren** [comment]
Right, You can register for the BOOT_COMPLETED broadcast. https://stackoverflow.com/questions/5290141/android-broadcastreceiver-on-startup-keep-running-when-activity-is-in-backgrou

However, I don't have an OnePlus device with me at the moment so I cannot test this. PRs are welcome.
